### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by shilpa-relysys** [sipeed/MF1-User-Manual#2]
1.If i gave thebelow  command through com tool for Mf1 board i got
 cmd: { "version": 1, "type": "init", "code":0,"msg": "init done","version":"v2.0" }
 Result:{"version":2,"type":"pkt_prase_failed_ret","code":1,"msg":"version should be 2,but we get 1","cmd":"unknown"}

2.if i change version to 2 ,i got the result as below 
 cmd:  { "version": 2, "type": "init", "code":0,"msg": "init done","version":"v2.0" }
result: {"version":2,"type":"pkt_prase_failed_ret","code":1,"msg":"unsupport command 
type","cmd":"unknown"}

**Comment by xelll** [comment]
init is MF1 send, it did not parse it, so return pkt_prase_failed_ret, you can send other command.

**Comment by shilpa-relysys** [comment]
for all the commands it was showing cmd unknown,msg:unknown command type

**Comment by xelll** [comment]
can you send this command 

`{"version":2,"type":"add_user_spec_uid","user":{"uid":"EDE6E800A20000000000000000000000","time_s":5}}
`

**Comment by shilpa-relysys** [comment]
For this command it was working fine

**Comment by shilpa-relysys** [comment]
Hello,

     while changing the value of GPIO's unfortunately i have changed the
ISP gpio's . so i am not able to flash the firmware to MF1 board. can you
please guide me regarding this issue?

Thanks and Regards
Shilpa

**Comment by xelll** [comment]
if you still need help,please reopen this issue
