### ISSUE TITLE
MF1 AI+IoT(Maix-Face V1.2) No Image on display

### ISSUE THREAD

**Issue by mightChamp** [sipeed/MF1-User-Manual#5]
![image](https://user-images.githubusercontent.com/45094530/86443482-f41d6800-bd2c-11ea-8fa7-f7597fb04819.png)

I am using this module.
I flash the latest firmware of maixpy_v0.5.0_95_g05c4e70.bin
to use with maixpy IDE. I can flash it successfully, and also send hello.py code to the device with selection of Sipeed Maix With Mic(Bit) as suggested in MF1-Usermanual. 
In Maixpy IDE, I can see thermal camera like images, but not getting colour images, and there is no output on TFT display.
I also tried arduino code but none of the TFT display code works.
I want the camera to capture  the image and display it on TFT.

Also On default factory firmware(checked on other device) I can't use json Uart communication method, there is no response for json command. Is there different firmware for it, where to find this one?

Please help regarding this.

Thank You

**Comment by myuanz** [comment]
MaxiPy do not support  MF1, if there is any other problem about MF1, feel free to email us.

**Comment by RONINSESSANTOTTO** [comment]
Hello
could you send me or give me indications on the installed firmware? My son bought the same module but he deleted the whole card and now I can't figure out which firmware to flash. He is only interested in offline facial recognition. Thank you very much
