### ISSUE TITLE
连接串口无法正常通讯

### ISSUE THREAD

**Issue by lzlz99** [sipeed/MF1-User-Manual#6]
1. 使用串口通讯工具与MF1通讯时，一连接上COM5，就不断接收到一些数据（请看附图）；根据通讯协议发送一些消息过去， 没有回应。 
2.使用COM6端口连接，能连接成功，发送数据没有回应。
3. 我使用一个python 编写个程序读取串口数据，和上述一样的现象。

 ps. 我的电脑配置： 微软 surface pro5，只有一个usb3.0的端口。使用的数据线是从你们淘宝店购买的。com口已经安装FTDI驱动（见附图）
![image](https://user-images.githubusercontent.com/25578110/88131797-64bef280-cc10-11ea-9f51-81ee7fcdd813.png)
![image](https://user-images.githubusercontent.com/25578110/88131806-6c7e9700-cc10-11ea-831a-bbed92de9ebd.png)
![image](https://user-images.githubusercontent.com/25578110/88131816-730d0e80-cc10-11ea-8410-fc092e28bd6b.png)
![image](https://user-images.githubusercontent.com/25578110/88131828-7a341c80-cc10-11ea-9844-73cd4c07f76a.png)
![image](https://user-images.githubusercontent.com/25578110/88131837-7f916700-cc10-11ea-824d-3fc86ca28abe.png)

**Comment by lzlz99** [comment]
![image](https://user-images.githubusercontent.com/25578110/88135323-56290900-cc19-11ea-9750-98f1b735c906.png)

这个MF1模块购于2020-7-20， 收到时已经组装好， 只需要插上usb供电就行了。 模块上面的小屏幕能检测出人脸，注册后也能识别，只是在串口通讯时就出现这些问题。

我电脑是win 10， 64位。电脑上自带了一个usb3.0。

**Comment by xelll** [comment]
这个请联系我们的support。
